-- MySQL Script generated by MySQL Workbench
-- Wed Sep  1 20:09:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oneFigure
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `oneFigure` ;

-- -----------------------------------------------------
-- Schema oneFigure
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oneFigure` DEFAULT CHARACTER SET utf8 ;
USE `oneFigure` ;

-- -----------------------------------------------------
-- Table `oneFigure`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oneFigure`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `oneFigure`.`Usuario` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `balance` DOUBLE NOT NULL DEFAULT 100,
  `password` VARCHAR(45) NOT NULL,
  `login` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oneFigure`.`Figure`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oneFigure`.`Figure` ;

CREATE TABLE IF NOT EXISTS `oneFigure`.`Figure` (
  `idFigure` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `rarity` VARCHAR(10) NOT NULL,
  `path` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFigure`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oneFigure`.`Album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oneFigure`.`Album` ;

CREATE TABLE IF NOT EXISTS `oneFigure`.`Album` (
  `idUser` INT NOT NULL,
  `idFigure` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT 0,
  INDEX `fk_Usuario_has_Figura_Figura1_idx` (`idFigure` ASC),
  INDEX `fk_Usuario_has_Figura_Usuario_idx` (`idUser` ASC),
  PRIMARY KEY (`idFigure`, `idUser`),
  CONSTRAINT `fk_Usuario_has_Figura_Usuario`
    FOREIGN KEY (`idUser`)
    REFERENCES `oneFigure`.`Usuario` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Usuario_has_Figura_Figura1`
    FOREIGN KEY (`idFigure`)
    REFERENCES `oneFigure`.`Figure` (`idFigure`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
