-- MySQL Script generated by MySQL Workbench
-- Sun Aug 29 18:54:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oneFigure
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `oneFigure` ;

-- -----------------------------------------------------
-- Schema oneFigure
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oneFigure` DEFAULT CHARACTER SET utf8 ;
USE `oneFigure` ;

-- -----------------------------------------------------
-- Table `oneFigure`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oneFigure`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `oneFigure`.`Usuario` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `balance` DOUBLE NOT NULL DEFAULT 100,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oneFigure`.`Rarity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oneFigure`.`Rarity` ;

CREATE TABLE IF NOT EXISTS `oneFigure`.`Rarity` (
  `idRarity` INT NOT NULL,
  `describe` VARCHAR(450) NULL,
  PRIMARY KEY (`idRarity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oneFigure`.`Figure`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oneFigure`.`Figure` ;

CREATE TABLE IF NOT EXISTS `oneFigure`.`Figure` (
  `idFigure` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `describe` VARCHAR(450) NULL,
  `idRarity` INT NOT NULL,
  `path` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFigure`),
  INDEX `fk_Figura_Rarity1_idx` (`idRarity` ASC),
  CONSTRAINT `fk_Figura_Rarity1`
    FOREIGN KEY (`idRarity`)
    REFERENCES `oneFigure`.`Rarity` (`idRarity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oneFigure`.`Album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oneFigure`.`Album` ;

CREATE TABLE IF NOT EXISTS `oneFigure`.`Album` (
  `idUser` INT NOT NULL,
  `idFigure` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT 0,
  INDEX `fk_Usuario_has_Figura_Figura1_idx` (`idFigure` ASC),
  INDEX `fk_Usuario_has_Figura_Usuario_idx` (`idUser` ASC),
  PRIMARY KEY (`idFigure`, `idUser`),
  CONSTRAINT `fk_Usuario_has_Figura_Usuario`
    FOREIGN KEY (`idUser`)
    REFERENCES `oneFigure`.`Usuario` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Usuario_has_Figura_Figura1`
    FOREIGN KEY (`idFigure`)
    REFERENCES `oneFigure`.`Figure` (`idFigure`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oneFigure`.`lastLogin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oneFigure`.`lastLogin` ;

CREATE TABLE IF NOT EXISTS `oneFigure`.`lastLogin` (
  `idlastLogin` INT NOT NULL AUTO_INCREMENT,
  `lastLogin` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idlastLogin`),
  INDEX `fk_lastLogin_Usuario1_idx` (`idUser` ASC),
  CONSTRAINT `fk_lastLogin_Usuario1`
    FOREIGN KEY (`idUser`)
    REFERENCES `oneFigure`.`Usuario` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
